#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR

CGI_DIR=$CODE_DIR/../../cgi-bin

if [ -d $CGI_DIR ]; then
    cp scripts/hydro.cgi $CGI_DIR
fi

exit $?
